### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/d2-docker#5]
### Issue description

- If the user has a container that does not expose any port the ``start`` command will fail
- We do not filter the ``docker ps`` query for DHIS2 dockers

### 💻 Console output

```
[d2-docker:INFO] Start image: eyeseetea/dhis2-data:2.30-sierra
[d2-docker:DEBUG] Run: docker ps "--format={{.Names}} {{.Ports}}"
Traceback (most recent call last):
  File "./bin/d2-docker.py", line 55, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./bin/d2-docker.py", line 48, in main
    return args.func(args)
  File "/home/sfera/docker/d2-docker/bin/commands/start.py", line 37, in run
    start(args, image_or_file)
  File "/home/sfera/docker/d2-docker/bin/commands/start.py", line 57, in start
    result = utils.get_image_status(image_name)
  File "/home/sfera/docker/d2-docker/bin/utils/utils.py", line 125, in get_image_status
    container_name, ports = parts
ValueError: not enough values to unpack (expected 2, got 1)
```

### 🐞 Debugging

parts value:

```
['gitea_server_1', '0.0.0.0:2222->22/tcp, 0.0.0.0:9093->3000/tcp']
['media-server_sonarr_1', '0.0.0.0:8989->8989/tcp']
['media-server_deluge_1', '58846/tcp, 58946/tcp, 58946/udp, 0.0.0.0:8987->8112/tcp']
['ouroboros-updated']
```

**Comment by SferaDev** [comment]
### Fix proposal

./bin/utils/utils.py

```python
def get_image_status(image_name, first_port=8080):
    final_image_name = image_name or get_running_image_name()
    project_name = get_project_name(final_image_name)
+    result = run(["docker", "ps", "--filter", "volume=/DHIS2_home", "--format={{.Names}} {{.Ports}}"], capture_output=True)
-    result = run(["docker", "ps", "--format={{.Names}} {{.Ports}}"], capture_output=True)
    output_lines = result.stdout.decode("utf-8").splitlines()
```
